[package]
name = "engine-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
engine-core = { path = "../engine-core" }

[dev-dependencies]
console_error_panic_hook = "0.1"
